#!/usr/bin/env sh

# This command is the one that loads the scripting addition
# Configure your user to execute `yabai --load-sa` as the root user without having to enter a password.
#  https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# In order to prevent simple-bar freezing upon yabai restart, you'll need to add
# this line at the start of your .yabairc file
# https://www.jeantinland.com/toolbox/simple-bar/documentation/installation/#update-your-yabai-config
osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'

# To see if there's errors with your yabai config:
# cat /tmp/yabai_linkarzu.err.log
# To see debug (echo) commands in this file:
# cat /tmp/yabai_linkarzu.out.log

yabai -m config layout bsp

###############################################################################
#                          Custom padding settings                            #
###############################################################################

yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

###############################################################################
#                             Window Config                                   #
###############################################################################

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# window animations
yabai -m config window_animation_duration 0.25
yabai -m config window_animation_easing ease_out_circ

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity on
# yabai -m config active_window_opacity 0.95
# yabai -m config normal_window_opacity 0.95
yabai -m rule --add app="Code" opacity=0.85

# set focus to follow mouse
yabai -m config focus_follows_mouse autoraise

###############################################################################
#                                   Rules                                     #
###############################################################################

for name in \
	'Messages' \
	'System Settings' \
	'Finder' \
	'Clock' \
	'Calendar' \
	'melonDS' \
	'iPhone Mirroring' \
	'Discord' \
	'RuneLite' \
	'Reminders' \
	'Notes' \
	'GitHub Desktop' \
	'Raycast' 
do
	yabai -m rule --add app="^${name}$" manage=off
done

